### ISSUE TITLE
Recover Wallet With Keys not getting past white screen after entering info

### ISSUE THREAD

**Issue by djcaelum** [safex/wallet#6]
I am on MacOS 10.13.4, and attempted to enter my Address, Secret SpendKey, and Secret ViewKey. After I enter the password and hit the "Recover" button, the application GUI turns white. I have left it for a few minutes with no progress. I watched this video, https://www.youtube.com/watch?v=-GNlI1MpBfs&feature=youtu.be .  I am not getting to the "Please wait while your wallet is being created" state in the GUI.

**Comment by RBate88** [comment]
Please download and install the current OSX binary. It's been updated in the last few hours to fix the grey/blue screen some OSX users are facing.

**Comment by djcaelum** [comment]
I am still getting the grey screen with no progress after entering keys and password, after naming my wallet file and clicking save.

**Comment by RBate88** [comment]
> I am still getting the grey screen with no progress after entering keys and password, after naming my wallet file and clicking save.

Can you confirm which OSX version you are on?

**Comment by djcaelum** [comment]
OSX: 10.13.4 (17E202)
iMac (27-inch, Mid 2010)
3.2 GHz Intel Core i3
16 GB 1333 MHz DDR3

**Comment by LunnySenior** [comment]
Yep, still getting a white/grey screen here every time I try to recover wallet with keys.

Macbook Pro Mid 2012
OSX: 10.13.5
2.9 Intel Core i7
16GB 1600MHz DDR3

**Comment by ddabek** [comment]
out dated operating systems

**Comment by LunnySenior** [comment]
Outdated? Im only .1 behind the latest OSX?

Ad

**Comment by djcaelum** [comment]
You are really going to leave your community out in the cold like this? For some people, we are running the most up to date that we can. My earlier than 2012 iMac is not supported by the new Mojave os. Is there no plan to support High Sierra?
